name: Accelerera
favicon: null
layout_spectrum: 0.34904850902967155
typography_spectrum: 0.5278278710320592
title: >-
  The Home of Accelerera Ltd, the UK's leading electric car race engineering
  team 
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#ffffff'
    - '#666465'
    - '#a7a6a6'
    - '#dbd9da'
  brandStrength: 0.6324426191858947
  lightness: 0.8766789527144283
  saturation: 0.6867478892672807
  rhythmicContrast: 0.11039498774334788
purpose: []
